"""changed to mysql

Revision ID: 71da2a23aebf
Revises: 
Create Date: 2023-09-12 23:28:45.860192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '71da2a23aebf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_role',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False, comment='用户权限ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='用户权限名称'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='用户权限描述'),
    sa.Column('permission', sa.String(length=255), nullable=True, comment='用户权限'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_role_id'), 'user_role', ['id'], unique=True)
    op.create_index(op.f('ix_user_role_name'), 'user_role', ['name'], unique=True)
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=128), nullable=False, comment='用户ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=254), nullable=True, comment='用户邮箱'),
    sa.Column('hashed_password', sa.String(length=128), nullable=False, comment='用户密码'),
    sa.Column('country_code', sa.String(length=10), nullable=False, comment='国家代码'),
    sa.Column('phone_number', sa.String(length=20), nullable=False, comment='手机号码'),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'phone_number', name='uq_countrycode_phonenumber')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('social_account',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False, comment='用户社交ID'),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False, comment='第三方平台用户ID'),
    sa.Column('access_token', sa.String(length=255), nullable=False, comment='第三方平台用户访问令牌'),
    sa.Column('refresh_token', sa.String(length=255), nullable=False, comment='第三方平台用户刷新令牌'),
    sa.Column('expires_at', sa.Date(), nullable=False, comment='第三方平台用户令牌过期时间'),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_account_id'), 'social_account', ['id'], unique=True)
    op.create_table('user_role_link',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('users_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['user_role.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('users_id', 'role_id')
    )
    op.drop_table('role')
    op.alter_column('user_profile', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('user_profile', 'id',
               existing_type=mysql.INTEGER(),
               comment='用户档案ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_profile', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               nullable=True,
               comment='用户姓名')
    op.alter_column('user_profile', 'nickname',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               nullable=True,
               comment='用户昵称')
    op.alter_column('user_profile', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True,
               comment='出生日期')
    op.alter_column('user_profile', 'avatar',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               comment='用户头像')
    op.alter_column('user_profile', 'bio',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               comment='用户简介')
    op.alter_column('user_profile', 'province',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               nullable=True,
               comment='省份')
    op.alter_column('user_profile', 'city',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               nullable=True,
               comment='城市')
    op.alter_column('user_profile', 'country',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               nullable=True,
               comment='国家')
    op.create_index(op.f('ix_user_profile_id'), 'user_profile', ['id'], unique=True)
    op.create_index(op.f('ix_user_profile_name'), 'user_profile', ['name'], unique=False)
    op.create_index(op.f('ix_user_profile_nickname'), 'user_profile', ['nickname'], unique=False)
    op.alter_column('user_profile_address', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('user_profile_address', 'id',
               existing_type=mysql.INTEGER(),
               comment='用户地址ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_profile_address', 'street',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               comment='街道')
    op.alter_column('user_profile_address', 'city',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               nullable=True,
               comment='城市')
    op.alter_column('user_profile_address', 'state',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               nullable=True,
               comment='省份')
    op.alter_column('user_profile_address', 'postal_code',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=20),
               nullable=True,
               comment='邮政编码')
    op.alter_column('user_profile_address', 'country',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               nullable=True,
               comment='国家')
    op.create_index(op.f('ix_user_profile_address_id'), 'user_profile_address', ['id'], unique=True)
    op.alter_column('user_profile_company', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('user_profile_company', 'id',
               existing_type=mysql.INTEGER(),
               comment='用户公司ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_profile_company', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               comment='公司名称')
    op.alter_column('user_profile_company', 'address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               comment='公司地址')
    op.alter_column('user_profile_company', 'phone_number',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=20),
               nullable=True,
               comment='公司电话')
    op.create_index(op.f('ix_user_profile_company_id'), 'user_profile_company', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profile_company_id'), table_name='user_profile_company')
    op.alter_column('user_profile_company', 'phone_number',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=255),
               nullable=False,
               comment=None,
               existing_comment='公司电话')
    op.alter_column('user_profile_company', 'address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               comment=None,
               existing_comment='公司地址')
    op.alter_column('user_profile_company', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               comment=None,
               existing_comment='公司名称')
    op.alter_column('user_profile_company', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='用户公司ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_profile_company', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_user_profile_address_id'), table_name='user_profile_address')
    op.alter_column('user_profile_address', 'country',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               nullable=False,
               comment=None,
               existing_comment='国家')
    op.alter_column('user_profile_address', 'postal_code',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=255),
               nullable=False,
               comment=None,
               existing_comment='邮政编码')
    op.alter_column('user_profile_address', 'state',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               nullable=False,
               comment=None,
               existing_comment='省份')
    op.alter_column('user_profile_address', 'city',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               nullable=False,
               comment=None,
               existing_comment='城市')
    op.alter_column('user_profile_address', 'street',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               comment=None,
               existing_comment='街道')
    op.alter_column('user_profile_address', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='用户地址ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_profile_address', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_user_profile_nickname'), table_name='user_profile')
    op.drop_index(op.f('ix_user_profile_name'), table_name='user_profile')
    op.drop_index(op.f('ix_user_profile_id'), table_name='user_profile')
    op.alter_column('user_profile', 'country',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               nullable=False,
               comment=None,
               existing_comment='国家')
    op.alter_column('user_profile', 'city',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               nullable=False,
               comment=None,
               existing_comment='城市')
    op.alter_column('user_profile', 'province',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               nullable=False,
               comment=None,
               existing_comment='省份')
    op.alter_column('user_profile', 'bio',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               comment=None,
               existing_comment='用户简介')
    op.alter_column('user_profile', 'avatar',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               comment=None,
               existing_comment='用户头像')
    op.alter_column('user_profile', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False,
               comment=None,
               existing_comment='出生日期')
    op.alter_column('user_profile', 'nickname',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               nullable=False,
               comment=None,
               existing_comment='用户昵称')
    op.alter_column('user_profile', 'name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               nullable=False,
               comment=None,
               existing_comment='用户姓名')
    op.alter_column('user_profile', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='用户档案ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_profile', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_table('role',
    sa.Column('modified_at', mysql.DATETIME(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role_name', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.drop_table('user_role_link')
    op.drop_index(op.f('ix_social_account_id'), table_name='social_account')
    op.drop_table('social_account')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_role_name'), table_name='user_role')
    op.drop_index(op.f('ix_user_role_id'), table_name='user_role')
    op.drop_table('user_role')
    # ### end Alembic commands ###
