"""fix user table bug

Revision ID: b2c4530b7678
Revises: b9102b01e0fa
Create Date: 2023-09-21 03:41:56.150575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b2c4530b7678'
down_revision: Union[str, None] = 'b9102b01e0fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               existing_comment='用户名')
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True,
               existing_comment='用户密码')
    op.alter_column('users', 'country_code',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               existing_comment='国家代码')
    op.alter_column('users', 'phone_number',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True,
               existing_comment='手机号码')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False,
               existing_comment='手机号码')
    op.alter_column('users', 'country_code',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               existing_comment='国家代码')
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False,
               existing_comment='用户密码')
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               existing_comment='用户名')
    # ### end Alembic commands ###
