"""fix social table

Revision ID: e0d0a0369981
Revises: ad1bc50acfa8
Create Date: 2023-09-21 02:22:44.668015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0d0a0369981'
down_revision: Union[str, None] = 'ad1bc50acfa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('social_account', 'expires_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_comment='第三方平台用户令牌过期时间',
               existing_nullable=False)
    op.create_unique_constraint(None, 'social_account', ['user_id', 'provider'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'social_account', type_='unique')
    op.alter_column('social_account', 'expires_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_comment='第三方平台用户令牌过期时间',
               existing_nullable=False)
    # ### end Alembic commands ###
