"""init

Revision ID: e95b42a48063
Revises: 
Create Date: 2023-09-23 02:09:10.150044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e95b42a48063'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False, comment='权限ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='权限名称'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='权限描述'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_id'), 'permission', ['id'], unique=True)
    op.create_index(op.f('ix_permission_name'), 'permission', ['name'], unique=True)
    op.create_table('user_profile',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False, comment='用户档案ID'),
    sa.Column('name', sa.String(length=50), nullable=True, comment='用户姓名'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='用户昵称'),
    sa.Column('date_of_birth', sa.Date(), nullable=True, comment='出生日期'),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', 'OTHER', name='sexenum'), nullable=True, comment='性别'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='用户头像'),
    sa.Column('bio', sa.String(length=255), nullable=True, comment='用户简介'),
    sa.Column('province', sa.String(length=50), nullable=True, comment='省份'),
    sa.Column('city', sa.String(length=50), nullable=True, comment='城市'),
    sa.Column('country', sa.String(length=50), nullable=True, comment='国家'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profile_id'), 'user_profile', ['id'], unique=True)
    op.create_index(op.f('ix_user_profile_name'), 'user_profile', ['name'], unique=False)
    op.create_index(op.f('ix_user_profile_nickname'), 'user_profile', ['nickname'], unique=False)
    op.create_table('user_role',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False, comment='角色ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='角色名称'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='角色描述'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_role_id'), 'user_role', ['id'], unique=True)
    op.create_index(op.f('ix_user_role_name'), 'user_role', ['name'], unique=True)
    op.create_table('role_permission_link',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['user_role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_profile_address',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False, comment='用户地址ID'),
    sa.Column('street', sa.String(length=255), nullable=True, comment='街道'),
    sa.Column('city', sa.String(length=50), nullable=True, comment='城市'),
    sa.Column('state', sa.String(length=50), nullable=True, comment='省份'),
    sa.Column('postal_code', sa.String(length=20), nullable=True, comment='邮政编码'),
    sa.Column('country', sa.String(length=50), nullable=True, comment='国家'),
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profile_address_id'), 'user_profile_address', ['id'], unique=True)
    op.create_table('user_profile_company',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False, comment='用户公司ID'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='公司名称'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='公司地址'),
    sa.Column('phone_number', sa.String(length=20), nullable=True, comment='公司电话'),
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profile_company_id'), 'user_profile_company', ['id'], unique=True)
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=128), nullable=False, comment='用户ID'),
    sa.Column('username', sa.String(length=50), nullable=True, comment='用户名'),
    sa.Column('email', sa.String(length=254), nullable=True, comment='用户邮箱'),
    sa.Column('hashed_password', sa.String(length=128), nullable=True, comment='用户密码'),
    sa.Column('country_code', sa.String(length=10), nullable=True, comment='国家代码'),
    sa.Column('phone_number', sa.String(length=20), nullable=True, comment='手机号码'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DELETED', 'BLOCKED', 'LOCKED', 'PENDING', name='usersstatusenum'), nullable=False, comment='用户状态'),
    sa.Column('user_profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'phone_number', name='uq_countrycode_phonenumber')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('social_account',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False, comment='用户社交ID'),
    sa.Column('provider', sa.Enum('GOOGLE', 'FACEBOOK', 'TWITTER', 'GITHUB', 'LINKEDIN', 'WEIBO', 'WEIXIN', 'QQ', 'ALIPAY', name='providerenum'), nullable=False, comment='第三方平台'),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False, comment='第三方平台用户ID'),
    sa.Column('access_token', sa.String(length=255), nullable=False, comment='第三方平台用户访问令牌'),
    sa.Column('refresh_token', sa.String(length=255), nullable=False, comment='第三方平台用户刷新令牌'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='第三方平台用户令牌过期时间'),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider')
    )
    op.create_index(op.f('ix_social_account_id'), 'social_account', ['id'], unique=True)
    op.create_table('user_role_link',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('users_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['user_role.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('users_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role_link')
    op.drop_index(op.f('ix_social_account_id'), table_name='social_account')
    op.drop_table('social_account')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_profile_company_id'), table_name='user_profile_company')
    op.drop_table('user_profile_company')
    op.drop_index(op.f('ix_user_profile_address_id'), table_name='user_profile_address')
    op.drop_table('user_profile_address')
    op.drop_table('role_permission_link')
    op.drop_index(op.f('ix_user_role_name'), table_name='user_role')
    op.drop_index(op.f('ix_user_role_id'), table_name='user_role')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_user_profile_nickname'), table_name='user_profile')
    op.drop_index(op.f('ix_user_profile_name'), table_name='user_profile')
    op.drop_index(op.f('ix_user_profile_id'), table_name='user_profile')
    op.drop_table('user_profile')
    op.drop_index(op.f('ix_permission_name'), table_name='permission')
    op.drop_index(op.f('ix_permission_id'), table_name='permission')
    op.drop_table('permission')
    # ### end Alembic commands ###
